### PR TITLE
task01. Narcissistic numbers.

### PR DESCRIPTION
**Pull request by YMikita**
Narcissistic numbers

### CODE REVIEW

**Comment by gruntoff** [comment]
` narcissisticNumbStr = str(divRemainder) + "**" + str(powers) + narcissisticNumbStr`

Please pay attention that there's a note in this task:
> Do not use str for digit manipulations at all, only pure math and loops.

Also you don't need to specify range like this `if 1 <= k <= 1000:`. You can use `for i in range(1001):` for that.

**Comment by YMikita** [comment]
> Do not use str for digit manipulations at all, only pure math and loops.

I thought it was just for number manipulation, this part is for perfect printing only.
Fixed.

> Also you don't need to specify range like this `if 1 <= k <= 1000:`. You can use `for i in range(1001):` for that.

Fixed.

**Comment by gruntoff** [comment]
You can replace `for i in range(1001):` with `for i in range(k+1):`. In that case you won't need `if i > k: break`.

For perfect printing you can use f-strings. Frankly speaking it is a learning objective of the next task, but you can try it out here too, if you decided to go with complex output. 

Also if you have input for a max integer, it would be nice if your code worked for input > 1000. It will be an easy fix

**Comment by YMikita** [comment]
> You can replace `for i in range(1001):` with `for i in range(k+1):`. In that case you won't need `if i > k: break`.
> 
> For perfect printing you can use f-strings. Frankly speaking it is a learning objective of the next task, but you can try it out here too, if you decided to go with complex output.
> 
> Also if you have input for a max integer, it would be nice if your code worked for input > 1000. It will be an easy fix

Fixed.

**Pull request merged**
