### PR TITLE
Task02

### PR DESCRIPTION
**Pull request by YMikita**
Area of a triangle

### CODE REVIEW

**Comment by gruntoff** [comment]
Please use f-string to format output. Output like this doesn't look very good.
Screenshot 2021-09-21 at 16 15 31

You can parse input like this
`base, height = map(float, parameters.split())`
It is shorter and more pythonic.

And finally, as for me, the code looks a bit too complicated for such task. What do you think? 😊

**Comment by YMikita** [comment]
> Please use f-string to format output. Output like this doesn't look very good.
> Screenshot 2021-09-21 at 16 15 31
> 
> You can parse input like this
> `base, height = map(float, parameters.split())`
> It is shorter and more pythonic.
> 
> And finally, as for me, the code looks a bit too complicated for such task. What do you think? 😊

Fixed.

**Comment by gruntoff** [comment]
There is no need to round your result `area_value = round(action(get_triangle_calc_variable(title)))`.
You can just format it while printing with [f-string](https://docs.python.org/3/tutorial/inputoutput.html#input-and-output) and [format specification](https://docs.python.org/3/library/string.html#formatspec).
For example `print(f'Area is: {area:.2f}')`

**Comment by YMikita** [comment]
> There is no need to round your result `area_value = round(action(get_triangle_calc_variable(title)))`.
> You can just format it while printing with [f-string](https://docs.python.org/3/tutorial/inputoutput.html#input-and-output) and [format specification](https://docs.python.org/3/library/string.html#formatspec).
> For example `print(f'Area is: {area:.2f}')`

Fixed.

**Pull request merged**
