### PR TITLE
task03.  Word stats.

### PR DESCRIPTION
**Pull request by YMikita**
Word stats.

### CODE REVIEW

**Comment by gruntoff** [comment]
You can try to use list `count()` method to count number of words

**Comment by YMikita** [comment]
> You can try to use list `count()` method to count number of words

Done.

**Comment by gruntoff** [comment]
I changed statuses of both tasks to "pass", but you can watch the recording of todays call (if you was not on the call) to see good laconic solutions.

**Comment by YMikita** [comment]
> I changed statuses of both tasks to "pass", but you can watch the recording of todays call (if you was not on the call) to see good laconic solutions.

Ok.
Thank you.

**Pull request merged**
